PAYARA-3493: Do not eagerly construct converter
payara/patched-src-eclipselink pull request #2
Opened 2019-03-20 14:20 UTC by pdudits

CDI is not yet available at creation time, and failure to obtain bean manager means, that CDI is not used at all to manage converters and listeners.

2019-03-20 14:45 UTC, jGauravGupta approved these changes

2019-03-21 13:55 UTC, Pandrex247 approved these changes

2019-03-21 14:31 UTC, arjantijms requested changes
ConverterClass should have the copyright updated, extra important for upstream PR

2019-03-22 10:46 UTC, arjantijms approved these changes

2019-03-22 10:46 UTC, merged